csv: "/home/local-admin/Hesam/VS/Chimera_cadgen-main/tif_paths.csv"

output_dir: "output" # output directory

tiling:
  backend: "openslide" 
  params:
    spacing: 1.9402779050190384 # spacing at which to tile the slide, in microns per pixel
    tile_size: 224 # size of the tiles to extract, in pixels

model:
  level: "tile" # level at which to extract the features ("tile", "region" or "slide")
  name: "uni"
  batch_size: 1